version: '3.8'

services:
  gemini:
    build: .
    container_name: gemini-cli
    tty: true
    stdin_open: true
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/root/.gemini
      - ./tools:/workspace/tools
      # Avoid overwriting /workspace/wrapper
      # - ./wrapper:/workspace/wrapper